## Getting Started with NumPy in Python

In [1]:
import numpy as np
import time

### Creating Arrays in NumPy

In [2]:
array1D = np.array([1,2,3,4,5])
print(array1D)

[1 2 3 4 5]


### Difference between arrays and list and their execution

In [9]:
start=time.time()
my_list = [i*2 for i in range(1000000)]
print("Time Taken for list: ",time.time()-start)

start=time.time()
my_array=np.arange(1000000)*2
print("Time Taken for array: ",time.time()-start)



Time Taken for list:  0.06703066825866699
Time Taken for array:  0.007002353668212891


### Creating arrays from scratch

In [14]:
zeros = np.zeros((4,4))
print(zeros)

ones = np.ones((4,4))
print("\n",ones)

full = np.full((2,2),5)
print("\n",full)

random = np.random.randint(0,10,size=(2,3))
print("\n",random)

sequence= np.arange(0,11,2)
print("\n",sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [[5 5]
 [5 5]]

 [[6 6 1]
 [3 9 2]]

 [ 0  2  4  6  8 10]


### Vectors, Matrices and Tensors

In [16]:
vector=np.array([1,2,3,5,6,7])
print(vector)

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("\n",matrix)

tensor=np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
print("\n",tensor)

[1 2 3 5 6 7]

 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Properties of Arrays

In [18]:
myArray=np.array([[1,2,3],[4,5,6]])
print(myArray.shape)
print(myArray.ndim)
print(myArray.size)
print(myArray.dtype)

(2, 3)
2
6
int64


### Reshaping the arrays

In [22]:
myArray=np.array([1,2,3,4,5,6])
print(myArray)
reshape=myArray.reshape((3,2))
print(reshape)
flattened=reshape.flatten() # return the copy
print(flattened)
raveled=reshape.ravel() #return the view instead of copy
print(raveled)
transpose=reshape.T


[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
