## Array Operations in NumPy

In [2]:
import numpy as np

### Indexing and Slicing

In [6]:
arr = np.array([1,2,3,4,5,7,8])
print(arr[2:7]) #basic slicing
print(arr[1:7:2]) #slicing with steps
print(arr[-4])

[3 4 5 7 8]
[2 4 7]
4


In [12]:
arr2D = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(arr2D[2,2]) #print specific element
print(arr2D[1]) #prits entire row
print(arr2D[:,1])


9
[4 5 6]
[2 5 8]


### Sorting arrays

In [15]:
array_unsorted = np.array([1,3,4,2,9,8,7,6])
print("Sorted: ",np.sort(array_unsorted))

Sorted:  [1 2 3 4 6 7 8 9]


In [19]:
arr2D_unsorted = np.random.randint(0,9,size=(3,3))
print(arr2D_unsorted)
print("Sorted by columns\n", np.sort(arr2D_unsorted, axis=0))
print("Sorted by rows\n", np.sort(arr2D_unsorted, axis=1))

[[4 5 7]
 [6 1 5]
 [4 6 8]]
Sorted by columns
 [[4 1 5]
 [4 5 7]
 [6 6 8]]
Sorted by rows
 [[4 5 7]
 [1 5 6]
 [4 6 8]]


### Filtering

In [23]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers=numbers[numbers%2==0]
print(even_numbers)

[ 2  4  6  8 10]


In [25]:
mask = numbers%2!=0
print(numbers[mask])

[1 3 5 7 9]


In [26]:
where_result = np.where(numbers>5)
print(numbers[where_result])

[ 6  7  8  9 10]


### Fancy Indexing and Conditonal Arrays using where

In [28]:
indices = [2,3,5,7,9]
print(numbers[indices])

[ 3  4  6  8 10]


In [29]:
conditonal_array=np.where(numbers>3,numbers*3,numbers)
print(conditonal_array)

[ 1  2  3 12 15 18 21 24 27 30]


### Adding and Removing Data

In [32]:
arr1 = np.array([2,3,5,7,9])
arr2 = np.array([4,3,7,8,10])
combined= np.concatenate((arr1,arr2))
print(combined)


[ 2  3  5  7  9  4  3  7  8 10]


In [34]:
# checking compatitblity for operations
print("The Arrays and compatible for addition: ",arr1.shape==arr2.shape)

The Arrays and compatible for addition:  True


In [36]:
my_array = np.array([[1,2,3],
                     [4,5,6],
                     [7,8,9]])
new_row = np.array([[5,1,8]])
print("Updated (Added Row) Array: ",np.vstack((my_array,new_row)))

Updated Array:  [[1 2 3]
 [4 5 6]
 [7 8 9]
 [5 1 8]]


In [40]:
new_col = np.array([[5],[1],[8]])
print("Updated (Added Columns) Array: ",np.hstack((my_array,new_col)))

Updated (Added Columns) Array:  [[1 2 3 5]
 [4 5 6 1]
 [7 8 9 8]]


In [45]:
print("Deleted 1st Row",np.delete(my_array,0,axis=0))

Deleted 1st Row [[4 5 6]
 [7 8 9]]


In [46]:
print("Deleted 1st Colums",np.delete(my_array,0,axis=1))

Deleted 1st Colums [[2 3]
 [5 6]
 [8 9]]
