## File I/O Operations on Arrays

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
array1= np.array([[1,2,3], [4,5,6]])
array2= np.random.randint(0,9,size=(3,2))
array3= np.full((3,3),4)

### Saving Arrays to File

In [4]:
np.save("array1.npy", array1)
np.save("array2.npy", array2)
np.save("array3.npy", array3)

### Loading Arrays from Files

In [5]:
loaded_array1 = np.load("array1.npy")
loaded_array2 = np.load("array2.npy")
loaded_array3 = np.load("array3.npy")

print(loaded_array1)
print(loaded_array2)
print(loaded_array3)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [8 6]
 [5 2]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]


### Loading and Displaying NumPy Logo

In [6]:
try:
    logo= np.load("numpy-logo.npy")
    
    plt.Figure(figsize=(10,10))
    plt.subplot(121)
    plt.imshow(logo)
    plt.title("Numpy Logo")
    plt.axis("off")
    plt.grid(False)
    
    dark_logo=1-logo
    plt.subplot(122)
    plt.imshow(dark_logo)
    plt.title("Numpy Dark Logo")
    plt.axis("off")
    plt.grid(False)

except FileNotFoundError:
    print("File Path not found")

File Path not found


## Data Types in NumPy

In [7]:
a = np.array([1, 2, 3], dtype=np.int32) #Integer
b = np.array([1.1, 2.2], dtype=np.float64) #float
c = np.array([True, False, True], dtype=np.bool_) #boolean
d = np.array([1+2j, 3+4j], dtype=np.complex64) #complex
e = np.array(["hello", "world"], dtype=np.str_) #String
f = np.array([1, "two", 3.0], dtype=np.object_) #Numpy Object (Mixed Arrays)

### Type Conversion

In [8]:
arr = np.array([1.5, 2.8, 3.2])
int_arr = arr.astype(np.int32)  # [1, 2, 3]
print(np.sctypeDict)  # Shows all scalar types

{'bool': <class 'numpy.bool'>, 'float16': <class 'numpy.float16'>, 'float32': <class 'numpy.float32'>, 'float64': <class 'numpy.float64'>, 'longdouble': <class 'numpy.longdouble'>, 'complex64': <class 'numpy.complex64'>, 'complex128': <class 'numpy.complex128'>, 'clongdouble': <class 'numpy.clongdouble'>, 'bytes_': <class 'numpy.bytes_'>, 'str_': <class 'numpy.str_'>, 'void': <class 'numpy.void'>, 'object_': <class 'numpy.object_'>, 'datetime64': <class 'numpy.datetime64'>, 'timedelta64': <class 'numpy.timedelta64'>, 'int8': <class 'numpy.int8'>, 'byte': <class 'numpy.int8'>, 'uint8': <class 'numpy.uint8'>, 'ubyte': <class 'numpy.uint8'>, 'int16': <class 'numpy.int16'>, 'short': <class 'numpy.int16'>, 'uint16': <class 'numpy.uint16'>, 'ushort': <class 'numpy.uint16'>, 'intc': <class 'numpy.intc'>, 'uintc': <class 'numpy.uintc'>, 'int32': <class 'numpy.int32'>, 'long': <class 'numpy.int32'>, 'uint32': <class 'numpy.uint32'>, 'ulong': <class 'numpy.uint32'>, 'int64': <class 'numpy.int64'

### Respresnting Data Types using Alphabets

In [9]:
bool_arr = np.array([True, False], dtype='b')  # 'b' for boolean

int8_arr = np.array([1, 2, 3], dtype='i1')     # 'i1' for int8 (1 byte)
int16_arr = np.array([1000], dtype='i2')       # 'i2' for int16 (2 bytes)
int32_arr = np.array([100000], dtype='i4')     # 'i4' for int32 (4 bytes)
int64_arr = np.array([10000000000], dtype='i8')# 'i8' for int64 (8 bytes)

uint8_arr = np.array([255], dtype='u1')        # 'u1' for uint8 (1 byte)
uint16_arr = np.array([65535], dtype='u2')     # 'u2' for uint16 (2 bytes)
uint32_arr = np.array([4294967295], dtype='u4')# 'u4' for uint32 (4 bytes)
uint64_arr = np.array([2**64 - 1], dtype='u8') # 'u8' for uint64 (8 bytes)

float16_arr = np.array([3.14], dtype='f2')     # 'f2' for float16 (2 bytes)
float32_arr = np.array([3.14], dtype='f4')     # 'f4' for float32 (4 bytes)
float64_arr = np.array([3.1415926535], dtype='f8') # 'f8' for float64 (8 bytes)

complex64_arr = np.array([1+2j], dtype='c8')   # 'c8' = 2 * float32 (8 bytes)
complex128_arr = np.array([1+2j], dtype='c16') # 'c16' = 2 * float64 (16 bytes)

bytes_arr = np.array([b'abc', b'def'], dtype='S3') # 'S3' = 3-byte ASCII strings

unicode_arr = np.array(['abc', 'def'], dtype='U3') # 'U3' = 3-character Unicode

object_arr = np.array([1, "two", 3.0], dtype='O')  # 'O' for Python object

datetime_arr = np.array(['2025-07-14'], dtype='M8[D]') # 'M8[D]' = datetime64 by day
timedelta_arr = np.array([10], dtype='m8[D]')          # 'm8[D]' = timedelta64 in days
